### ISSUE TITLE
Error when loading docx, xlsx...

### ISSUE THREAD

**Issue by RodriMora** [SillyTavern/SillyTavern-Office-Parser#1]
Hi!

I'm trying to load files but I get this error:

```
PayloadTooLargeError: request entity too large
    at l (/home/ubuntu/SillyTavern/plugins/SillyTavern-Office-Parser/dist/plugin.js:1:1457484)
    at e.exports (/home/ubuntu/SillyTavern/plugins/SillyTavern-Office-Parser/dist/plugin.js:1:1457110)
    at e.exports (/home/ubuntu/SillyTavern/plugins/SillyTavern-Office-Parser/dist/plugin.js:1:89720)
    at /home/ubuntu/SillyTavern/plugins/SillyTavern-Office-Parser/dist/plugin.js:1:91797
    at Layer.handle [as handle_request] (/home/ubuntu/SillyTavern/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/SillyTavern/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/home/ubuntu/SillyTavern/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/home/ubuntu/SillyTavern/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/SillyTavern/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/ubuntu/SillyTavern/node_modules/express/lib/router/index.js:346:12)
Uploaded file: /user/files/1716975540094_5246333393282262.txt from default-user
```

What is the limit for the files? It seems to work just fine with files under 100KB, but anything over that and it outputs this error.

**Comment by Cohee1207** [comment]
Yes, you're right, the limit is 100KB and should be raised. I'll do it in a while.

**Comment by RodriMora** [comment]
> Yes, you're right, the limit is 100KB and should be raised. I'll do it in a while.

Thanks a lot! 

Will using the Vectorization Source  as local reduce the file size? Would it be recommended to use the Extras server a it uses sentence-transformers/all-mpnet-base-v2 which I guess have a bigger context length?

**Comment by Cohee1207** [comment]
You can easily swap embedding models both for extras and local. For extras - with a command line flag. For local - with config.yaml. So there's no precise recommendation for what to use, feel free to try different options.

**Comment by Cohee1207** [comment]
This has been fixed. Update the plugin by running the following in the SillyTavern repository root:
```bash
npm run plugins:update
```
